artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/
  data_dir: artifacts/data
  local_data_file: artifacts/data/data.csv

data_validation:
  root_dir: artifacts/
  data_path: artifacts/data/data.csv
  glove_path: glove/glove.6B.50d.txt

model_trainer:
  root_dir: artifacts/
  data_path: artifacts/data/data.csv
  embed_file: glove/glove.6B.50d.txt
  models_dir: artifacts/models
  model_path: artifacts/models/model.h5
  tokenizer_path: artifacts/models/tokenizer.pickle
  embed_mat: artifacts/models/embedding_matrix.pickle
  validation_path: artifacts/data/validation.csv


model_evaluation:
  root_dir: artifacts/model_evaluation
  data_path: artifacts/data_transformation/samsum_dataset
  model_path: artifacts/models/model.h5
  tokenizer_path: artifacts/models/tokenizer.pickle
  embed_mat: artifacts/models/embedding_matrix.pickle
  validation_path: artifacts/data/validation.csv
  validation_output: artifacts/model_evaluation/validation_output.json
  confusion_matrix_path: artifacts/model_evaluation/confusion_matrix

